name: Uno Prefab Bug report
description: Template for bug reports regarding the UnoPrefab
title: '[UnoPrefab]: '
labels:
- bug
body:
  - type: dropdown
    id: BugType
    attributes:
      label: Bug Type
      description: What type of bug are you experiencing?
      options:
        - Networking
        - Functionality
        - Editor
        - Other
    validations:
      required: true
  - type: input
    id: UnoPrefabVersion
    attributes:
      label: UnoPrefab Version
      description: What number version of the UnoPrefab were you using?
      placeholder: '1_0_1'
    validations:
      required: true
  - type: textarea
    id: BugDescription
    attributes:
      label: Bug Description
      description: What happened?
      placeholder: Oh no, our table.... it's broken.
    validations:
      required: true
  - type: textarea
    id: ExpectedOutcome
    attributes:
      label: Expected Outcome
      description: What were you expecting to happen?
      placeholder: The table to not be broken.
    validations:
      required: true
  - type: textarea
    id: Reproduction
    attributes:
      label: Reproduction Steps
      description: How can I recreate your setup to experience this bug?
      placeholder: |-
        1. Approach Table
        2. Stack bricks on table
        3. Continue stacking bricks on table
        4. Repeat step 3 until the table shatters
    validations:
      required: true
